openaustralia/openaustralia-parser

lib/name.rb, spec/name_spec.rb
Sorry this is such a big PR @henare I got a bit carried away trying to understand how it all works :S
See https://github.com/openaustralia/openaustralia/issues/600 for the basic reason why this was happening. In the image downloader, the method needs to get the person’s name of their parlinfo bio page. In then uses this name to select the person it's targeting.
Running `bundle exec member-images.rb` on master produces some incorrect results:
* Pauline Hanson’s image is Sarah Hanson-Young’s image #600
* Sarah Hanson-Young’s image isn't downloaded using her id
* Peter Whish-Wilson’s image isn't downloaded
* Skye Kakoschke-Moore’s image isn't downloaded
* Concetta Anna Fierravanti-Wells’ image isn't downloaded
After these changes, images are downloaded and properly assigned for each of these …
=> Fix for image download for mps with hyphenated last names

data/senators.csv, lib/people_csv_reader.rb
Bernardi is now in Australian Conservatives. I've used 'AC' for that party
=> Updated parties for Cory Bernardi + Nick Xenophon

data/people.csv, data/senators.csv
Info for these changes - http://www.aph.gov.au/Senators_and_Members/Parliamentarian?MPID=270552
In a nut shell:
1) The High Court has declared that Gichuhi's term as a Senator is deemed to have started 1.7.2016 (as a Family First Senator, replacing Bob Day)
2) On 26.4.2017, the FFP merged with Bernardi's Aus Conservatives but Gichuhi has said no to joining and so is now an Independent from that date
These changes feel very odd! I mean, Gichuhi has yet to sit in the Senate but has already clocked up over six months of deemed service and a change in party! But I guess we should follow what her Parliamentary record says...
=> Added Lucy Gichuhi as new SA Senator

create_patch.rb
Unified diffs can be concatenated to apply multiple patches, so patching a patched file and appending the diff is sufficient.
=> Allow patches to accumulate

create_patch.rb, parse-speeches.rb
This provides a command-line interaction when parsing fails, if using `--interactive`, making it easy to create a patch for the current file. Without this, errors halt the parser, and it's easy to make errors in invoking create-patch.rb manually.
=> Errors during parsing allow user to patch/retry/continue/quit when --interactive

data/people.csv, data/senators.csv
https://www.aph.gov.au/Senators_and_Members/Parliamentarian?MPID=30484
replaces
https://www.aph.gov.au/Senators_and_Members/Parliamentarian?MPID=J7Q
=> Slade Brockman has replaced Christopher Beck in the Senate

data/senators.csv
On Fri 27 Oct 2017, the High Court rules Nash & Roberts ineligible thanks to dual citizenship
=> Senators Nash + Roberts disqualified

data/representatives.csv
On Fri 27 Oct 2017, High Court rules Joyce ineligible due to dual citizenship
=> Joyce disqualified

data/representatives.csv, lib/people_csv_reader.rb
New changes made:
- Barnaby Joyce is back in Parl, so he's been added once more
Corrections made for consistency:
- Several Qld LNP MPs were listed as belonging to "LIB" as opposed to "NP", despite the fact that their pages on aph.gov.au listing them as Nats rather than Libs. I've changed all these.
- One Qld LNP MP was listed as "LNP" despite none others being listed as such, so I've changed it to make it consistent (in that case, he was a LIB)
- One NSW NP MP had their party listed as "Nats" so I changed that as "NP" like all the others
- Katter was listed as IND when he has been part of Katter Aus Party since 2011 (**I've now listed him as KAP, but does a change need to be made anywhere else to make clear that KAP stands for Katter Aus Party?**)
=> Update House of Reps

data/senators.csv
Sam Dastayari resigned 25.1.2018
Fraser Anning changed to independent 15.1.2018
Also, minor change to number of Rex Patrick - was listed as no. 888 but should be 878 (think this was typo).
There are two other changes coming to our senators (Brandis leaving, Gichuhi going to Libs) but as these changes aren't official on their APH records yet, am leaving them as they are for now.
=> Dastayari resigned, Anning indep.

data/people.csv
Have added entry for David Smith (Labor) and added Dean Smith (Liberal)'s full name to his entry so he stops being mixed up with David Smith (due to both being D Smith).
In the week beginning 18 June 2018, they were mixed up due to this issue, so it's vital that both D Smith's have their middle names recorded in our data (Hansard is now listing them as DA Smith and DPB Smith to avoid this issue)
=> David Smith enters Senate

data/senators.csv
Declared elected 23.5.18 (replacing K Gallagher)
=> David Smith new Labor Senator for ACT

data/senators.csv, lib/people_csv_reader.rb
Nick Xenophon Party changed name to Centre Alliance 10.4.2018 so I've changed Sen. Griff & Sen. Patrick's records to reflect this.
**Other change made:**
Labor Sen Katy Gallagher's election ruled void under s.44 Const 9.5.2018
=> Gallagher leaves + NXT becomes Centre Alliance

data/senators.csv
[Media reports](https://www.abc.net.au/news/2018-10-25/fraser-anning-dumped-from-katters-australian-party/10428482) that Anning left Katter Aus Party on 25 Oct 2018 (though APH website hasn't yet updated [their records](https://www.aph.gov.au/Senators_and_Members/Parliamentarian?MPID=273829) yet)
=> Anning leaves Katter Aus Party

data/representatives.csv
On [27 Nov 2018](https://www.afr.com/news/julia-banks-quits-liberal-party-to-become-independent-20181127-h18e99), MP Julia Banks left the Liberal Party to become an Independent
=> MP Julia Banks now Independent

data/senators.csv
Another change that got away - back on [2 Feb 2018](https://www.abc.net.au/news/2018-02-02/lucy-gichuhi-independent-senator-joins-liberal-party/9392018), Sen Lucy Gichuhi entered the Liberal Party
=> Sen Lucy Gichuhi now in Liberal Party

data/senators.csv
Sen Bushby resigned in January and Sen J Collins resigned this month.
Currently there is no announced replacement for Bushby - media suggests the Liberal Party want to replace him with a female candidate (which makes sense considering all the resignations recently...)
[Media reports](https://www.news.com.au/national/breaking-news/labor-shoppies-still-powerful-senator/news-story/2faa4976e0b995cffe514e864c6efeb0) say Collins will be replaced by Raff Ciccone, but this not yet confirmed
Right now, Parliament running with only 11 senators for Victoria and Tasmania (both should have 12)
=> Senators Bushby and J Collins resign

data/people.csv
[Wendy Askew](https://www.aph.gov.au/Senators_and_Members/Parliamentarian?MPID=009FX) and [Raff Ciccone](https://www.aph.gov.au/Senators_and_Members/Parliamentarian?MPID=281503) appointed 6.3.2019
=> New Senators Askew (Tas) and Ciccone (Vic)

data/people.csv, data/senators.csv
Senator [Wendy Askew](https://www.aph.gov.au/Senators_and_Members/Parliamentarian?MPID=009FX) has been [appointed](https://twitter.com/SenatorRyan/status/1103060049025392646) for Tas and Senator [Raff Ciccone](https://www.aph.gov.au/Senators_and_Members/Parliamentarian?MPID=281503) has been [appointed](https://twitter.com/SenatorRyan/status/1103193580116500480) for Vic
Senator [David Leyonhjelm](https://www.aph.gov.au/Senators_and_Members/Parliamentarian?MPID=111206) has resigned for NSW
=> Askew + Ciccone appointed; Leyonhjelm resigns

data/people.csv, data/senators.csv
S15 replacement for David Leyonhjelm from 20.3.2019
=> Add Duncan Spender - NSW LDP

data/senators.csv
ACT Senator David Smith [resigned 11.4.2019](https://www.aph.gov.au/Senators_and_Members/Parliamentarian?MPID=276714)
=> David Smith resigns

data/senators.csv
Jim Molan [has replaced](https://www.abc.net.au/news/2019-11-10/jim-molan-to-return-to-the-senate/11690736) Arthur Sinodinos for Senator of NSW after the latter resigned
=> Jim Molan replaced Arthur Sinodinos

data/people.csv
New senator for South Australia: [Andrew McLachlan](https://www.aph.gov.au/Senators_and_Members/Parliamentarian?MPID=287062)
=> Andrew McLachlan joins Senate

data/senators.csv
New SA Senator [Andrew McLachlan](https://www.aph.gov.au/Senators_and_Members/Parliamentarian?MPID=287062) replaces [Cory Bernardi](https://www.aph.gov.au/Senators_and_Members/Parliamentarian?MPID=G0D)
=> Bernardi resigns, replaced by McLachlan

data/representatives.csv
MP Mike Kelly [resigned 30.4.2020](https://www.aph.gov.au/Senators_and_Members/Parliamentarian?MPID=HRI) and has yet to be replaced. Due to the COVID-19 pandemic, the date of the forthcoming by-election has [yet to be announced](https://www.abc.net.au/news/elections/eden-monaro-by-election-2020/).
=> Eden-Monaro MP has resigned; spot currently vacant

data/people.csv
Eden-Monaro by-election on 4 July 2020.
=> Kristy McBain elected to Eden-Monaro

data/people.csv
Chosen by the Parliament of Victoria on 4.9.2020 under section 15 of the Constitution to represent that State in the Senate after R Di Natale (resigned).
=> Senator Lidia Thorpe appointed to Senate

data/senators.csv
Rex Patrick [leaves CA](https://www.abc.net.au/news/2020-08-10/sa-crossbench-senator-rex-patrick-quits-to-run-as-an-indepentent/12539822) to become an independent in August.
[Lidia Thorpe](https://www.aph.gov.au/Senators_and_Members/Parliamentarian?MPID=280304) appointed under section 15 to replace Di Natale as Victorian Senator. I have also created a [pull request to update the people.csv file](https://github.com/openaustralia/openaustralia-parser/pull/100)
=> Patrick changes parties + Thorpe appointed

data/representatives.csv
Groom MP John McVeigh [resigned 18.9.2020](https://www.aph.gov.au/Senators_and_Members/Parliamentarian?MPID=125865). By-election to be held [28 November 2020](https://www.aec.gov.au/groom/).
=> McVeigh MP resigned

data/senators.csv
Victorian Greens Senator Richard Di Natale [resigned on 26.8.2020](https://www.aph.gov.au/Senators_and_Members/Parliamentarian?MPID=53369). He has not yet been replaced and, with the COVID situation in Victoria, it might take a while for that to happen.
=> Di Natale resigned 26/08

data/senators.csv
His replacement has been named - Ben Small - but not yet signed off by WA Parliament, which should happen in late November.
=> Senator Cormann resigned 6/11

data/people.csv
[Ben Small](https://www.aph.gov.au/Senators_and_Members/Parliamentarian?MPID=291406) has replaced Senator Cormann
=> Ben Small joins Senate

data/representatives.csv
New MP for Groom [Garth Hamilton](https://www.aph.gov.au/Senators_and_Members/Parliamentarian?MPID=291387) was sworn in on 3/12/2020. By-election was held on 28/11/2020.
=> New MP for Groom Garth Hamilton

data/representatives.csv
MP for Hughes Craig Kelly [now an independent](https://www.abc.net.au/news/2021-02-23/craig-kelly-quits-liberal-party/13182994). Quit the Liberal Party on [23 Feb 2021](https://twitter.com/CraigKellyMP/status/1364063687082872832).
=> MP Craig Kelly quits LIB, now IND

data/ministers.csv
The latest Morrison ministry, properly called the "third" but for some reason titled the "second" (perhaps they are embarrassed about having so many changes so soon after the last lot). Updated 30 March 2021.
=> The second "Second" Morrison Ministry

data/ministers.csv
According to their official minister pages, [Joyce](https://www.aph.gov.au/Senators_and_Members/Parliamentarian?MPID=e5d) not only replaced [McCormack](https://www.aph.gov.au/Senators_and_Members/Parliamentarian?MPID=219646) in leading the party, but also took his portfolio in Infrastructure, Transport and Regional Development. This hasn't been updated in the Ministry list yet, but that will probably wait for Morrison to return to Australia.
=> Joyce replaces McCormack June '21

data/senators.csv
SA Senator Gallacher [passed away last week](https://www.abc.net.au/news/2021-08-30/sa-labor-senator-alex-gallacher-dies-after-lung-cancer-battle/100418876). A new SA senator has not yet been announced.
=> SA Sen Alex Gallacher has died 29.8.2021

data/people.csv
Senator Dorinda Cox has replaced Rachel Siewert as WA Senator with the Greens Party
=> New WA Senator Dorinda Cox

data/representatives.csv
[Tony Smith](https://www.aph.gov.au/Senators_and_Members/Parliamentarian?MPID=00APG) has been replaced by [Andrew Wallace](https://www.aph.gov.au/Senators_and_Members/Parliamentarian?MPID=265967) as Speaker 23.11.2021
=> New Speaker, from Smith to Wallace

data/people.csv
[Greg Mirabella](https://www.aph.gov.au/Senators_and_Members/Parliamentarian?MPID=286349) chosen by Vic Parliament for the Senate
=> New Victorian Senator - Mirabella

data/representatives.csv
I missed updating Craig Kelly's new party last year - since [23 Aug 2021](https://www.unitedaustraliaparty.org.au/craig-kelly-appointed-leader-of-the-united-australia-party/) he's been in United Australia Party
=> Craig Kelly to UAP

data/representatives.csv
Spence MP Nick Champion [resigned on 22.2.22](https://www.aph.gov.au/Senators_and_Members/Parliamentarian?MPID=HW9) to take part in SA election. He has not yet been replaced - perhaps won't before the election.
=> Spence MP Nick Champion resigned

data/senators.csv
Vic Senator Kitching [died in office on 10.3.2022](https://www.aph.gov.au/Senators_and_Members/Parliamentarian?MPID=247512). Her place has not yet been filled, and perhaps won't before the next election.
=> Vic Senator Kitching died in office

data/shadow-ministers.csv
I chose the date "01/06/2022" for when the previous shadow ministry ended, as that's the date the new Albanese ministry was released, and many of these former shadow ministry reps are now in the ministry.
I used "05/06/2022" for the new shadow ministry start date, as that's the date Dutton shadow ministry was released.
=> Dutton Shadow Ministry 05 June 2022

data/representatives.csv
On 23 Dec 2022, MP [Andrew Gee](https://en.wikipedia.org/wiki/Andrew_Gee_(politician)) announced he was leaving the Nationals and sitting as an Independent instead
=> Andrew Gee becomes independent

data/senators.csv
On 6 Feb 2023, [Lidia Thorpe](https://en.wikipedia.org/wiki/Lidia_Thorpe) announced that she's leaving the Greens and will now sit as an Independent
On 16 Jan 2023, [Jim Molan](https://en.wikipedia.org/wiki/Jim_Molan) died. There is now a vacancy in the Senate for NSW.
=> Lidia Thorpe becomes Independent, Jim Molan died

data/people.csv
Cameron Caldwell replaced Stuart Robert as MP for Fadden, so needs to be added.
=> Update people.csv - Cameron Caldwell

data/representatives.csv
Cameron Caldwell replaced Stuart Robert (who resigned) as MP for Fadden after a by-election in July.
=> Update representatives.csv - Caldwell (Fadden) and Broadbent (Monash)

data/senators.csv
David Van is now an independent.
From his [Senate homepage](https://www.aph.gov.au/Senators_and_Members/Parliamentarian?MPID=283601):
* Independent. Served: 19.06.2023 to present
* Liberal Party of Australia. Served: 01.07.2019 to 19.06.2023
=> Update senators.csv - Senator Van now IND

data/senators.csv
Senator [Marise Payne](https://www.aph.gov.au/Senators_and_Members/Parliamentarian?MPID=M56) resigned 30/09/2023
Former MP [Dave Sharma](https://www.aph.gov.au/Senators_and_Members/Parliamentarian?MPID=274506) was chosen to replace her 30/11/2023
=> Update senators.csv - Sharma replaced Payne as NSW Liberal Senator

data/senators.csv
Vic Senator Linda White [died in office 29.2.2024](https://www.aph.gov.au/Senators_and_Members/Parliamentarian?MPID=IWK). No one has yet been appointed to replace her.
=> Update senators.csv - VIC Senators

data/representatives.csv
MP Murphy (Dunkley) [has died in office](https://www.aph.gov.au/Senators_and_Members/Parliamentarian?MPID=133646). A by-election has taken place and [Jodie Belyea](https://en.wikipedia.org/wiki/Jodie_Belyea) was elected as of 2 March, but the aph website has not yet created a page for her.
MP Morrison (Cook) [has resigned](https://www.aph.gov.au/Senators_and_Members/Parliamentarian?MPID=E3L) and a [Cook by-election](https://en.wikipedia.org/wiki/2024_Cook_by-election) will be held, though the date is still to be confirmed.
=> Update representatives.csv - MPs for Dunkley and Cook
