- data/ministers.csv
Sorry could not run the parser but I am submitting this PR as per @henare comment on https://github.com/openaustralia/openaustralia/issues/612
> updated the data of the ministers.csv file as per Issue # 612

- data/senators.csv
To fix https://github.com/openaustralia/openaustralia/issues/622
> Update Dep President in Senate

- README.md
Fixes https://github.com/openaustralia/openaustralia/issues/627
> Add instructions on what to do when there's a scraper failure

- data/representatives.csv
More citizenship issues, another resignation
> John Alexander resigns

- data/senators.csv
More citizenship matters
Lambie & Xenophon resign
Steele-John, Bartlett & Anning appointed
> 2 more resignations + 3 appointments

- data/senators.csv
Senator Kakoschke-Moore resigned on 22 Nov after learning she too is a dual citizen.
Hopefully this will be the last of the dual citizen resignations, but who knows?
> Kakoschke-Moore latest to resign

- data/people.csv
Senator page: https://www.aph.gov.au/Senators_and_Members/Parliamentarian?MPID=FAB
> Jim Molan added

- data/people.csv
> Added Ged Kearney

- data/representatives.csv
Feeney resigned, Kearney elected
> Batman by-election: Feeney + Kearney

- data/senators.csv
Brandis resigned
Stoker + Storer appointed
> Brandis, Stoker + Storer

- data/people.csv
- data/representatives.csv
Hopefully fixes openaustralia/openaustralia/issues/637 (and therefore openaustralia/openaustralia/issues/636)
> Tim Hammond retired, Patrick Gorman elected

- data/representatives.csv
**QUERY: How to create new party?** 
(NB: This is the same question I listed at https://github.com/openaustralia/openaustralia-parser/pull/40 as change also required there)
Nick Xenophon Party changed name to Centre Alliance 10.4.2018 so, as well as recording her resignation, I've changed Sen. Sharkie's record to reflect this change BUT I'm unsure if it is enough to simply change party name from NXT to CA - is there somewhere else I need to register the party's new name and make clear that CA = "Centre Alliance"?
Many thanks!
(P.S. I think I've asked this same question before, but unfortunately I don't seem to have recorded the answer in my notes - apologies for repetition!)
**Following MPs resigned:**
* Labor MP Keay 10.5.2018
* Labor MP Wilson 10.5.2018
* Labor MP Lamb 10.5.2018
* Labor …
> 5 MP resignations + NXT becomes Centre Alliance

- data/senators.csv
Changed party to KAP in 4.6.2018
> Anning moved to Katter Party in June

- data/senators.csv
See issue here: https://github.com/openaustralia/publicwhip/issues/1178
> Correcting how K Keneally's start date showing up

- data/ministers.csv
We received an email flagging that B Joyce's information wasn't up to date on OA.org. After taking a look, I see that a few ministerial positions changed after he stepped down in February and so have made those changes
> Ministerial reshuffles after B Joyce's resignation

- data/representatives.csv
Patrick Gorman was already added, this adds everyone else.
> Add the rest of the 2018-07-28 re-elections

- data/ministers.csv
Can't update the rest of the ministry as the list hasn't yet been
published, but the leadership changes are confirmed.
> Liberal leadership changes, August 2018 edition

- data/representatives.csv
> Malcolm Turnbull's resignation

- data/shadow-ministers.csv
Senator Jacinta Collins has resigned and her positions have passed on to others
> Shadow Ministry List updated 18 Feb 2019

- data/ministers.csv
- data/people.csv
- data/senators.csv
Just noticed that the President of the Senate referred to Senator Raff Ciccone as "Rafael Ciccone" in [his tweet](https://twitter.com/SenatorRyan/status/1103193580116500480)
> Raff also known as Rafael

- data/ministers.csv
From [Ministry List](https://www.pmc.gov.au/resource-centre/government/ministry-list)
> Second Morrison Ministry 29 May 2019

- lib/hansard_parser.rb
to make it simpler to track down the location of any failures
> Emit some detail as debates are parsed

- Gemfile
- Gemfile.lock
- Update Gemfile to a set of dependencies that is installable, so that "bundle install" works.
> Improve local testing

- lib/configuration.rb
Previous iteration worked for test, but only in some cases for non-test
> Fix the loading of config in both test and non-test cases

- data/senators.csv
Victorian [Senator Fified](https://www.aph.gov.au/Senators_and_Members/Parliamentarian?MPID=D2I) (Lib) resigned and has been replaced by [Senator Henderson](https://www.aph.gov.au/Senators_and_Members/Parliamentarian?MPID=ZN4) on 11.9.2019
> Sen Henderson replaces Sen Fifield for Victoria

- data/ministers.csv
The Prime Minister announced on 6 February 2020, his intention to recommend to the Governor-General [this Ministry](https://www.pmc.gov.au/resource-centre/government/ministry-list)
> Proposed Ministry 6 February 2020

- data/ministers.csv
> The Second Morrison Ministry

- data/senators.csv
The Greens have announced that she will be replaced by Dorinda Coxto, but that change has not been made official yet.
> Senator Siewert has resigned

- data/senators.csv
Senator Cox replaces Senator Siewert as WA senator with the Greens Party
> WA Senator Dorinda Cox appointed

- data/senators.csv
New Senator for Victoria [Greg Mirabella](https://www.aph.gov.au/Senators_and_Members/Parliamentarian?MPID=286349) chosen by Vic Parliament
> Greg Mirabella enters parliament

- data/representatives.csv
NOTE:
One MP belongs to a new electorate: Hawke VIC
> Election 2022

- data/people.csv
New senators from the 2022 Election
> Election 2022 - new senators

- data/senators.csv
A new Speaker (Lines) and Deputy Speaker (McLachlan) have been appointed.
> Speaker + Deputy Speaker updated

- data/representatives.csv
A new Speaker (Dick) has been appointed
> Speaker update

- data/people.csv
[Jodie Belyea](https://www.aph.gov.au/Senators_and_Members/Parliamentarian?MPID=309484) has replaced MP Murphy (deceased) as MP for Dunkley
> Update people.csv - new MPs for Dunkley and Cook + two new VIC senators

- data/senators.csv
WA Senator [Fatima Payman](https://www.aph.gov.au/Senators_and_Members/Parliamentarian?MPID=300707) is now an independent
> Update senators.csv - Payman, Rennick and Tyrrell all independent

- .github/workflow/parent.yml
alerts the @openaustralia/openaustralia repo that this submodule has changed
> Add GitHub Actions workflow to update parent repository
